---
title: "README_BRGY"
author: "Gabriel Martin S. Ong"
date: "1/20/2022"
output: html_document
---
Calculations for population density of all Barangays in the Philippines

*We assume that all barangays in a particular region have equal land area. ((E.g. 
Area of Barangay in Region 1 = Area of Region 1/Number of Barangays in Region 1)

For our datasets, we have the ff:

regionarea.csv : A list of all regions and their corresponding Area
population.csv : List of barangay and their corresponding region, province, cityprovince, population, household population, and number of households

Preparing our data
 - In identifying the population density, we first need to know the number of Barangays per Region.

 - After creating the list of Barangay count per region, we merge it to the population.csv

 - We merge as well regionarea.csv with the updated population.csv.

Data Manipulation

1. Solve for the Barangay Area by dividing Region Area with number of Barangays.
    ```sh
      #Creating a new column for the Barangay Area
      population_3$barangay_area <- population_3$Area/population_3$n
    ```
2. After getting the Barangay Area, we can now solve for the density by dividing the Population by Barangay Area
    ```sh  
      #Creating a new column for the Population per Barangay Area
      population_3$density <- population_3$Population/population_3$barangay_area
    ```
3. In identifying the top 5 Barangays with the highest densities, we use the arrange and head functions 
    ```sh
      #Identifying the top 5 Barangays with the highest density
      top_barangay <- head(arrange(barangay_df,desc(density)), n = 5)
    ```
4. In identifying the top 5 Barangays with the highest densities per City, we use the arrange, groupby, and slice functions 
    ```sh
      #Top 5 per City
      per_city <- population_3 %>%
                  arrange(desc(density)) %>% 
                  group_by(CityProvince) %>%
                  slice(1:5)
      per_city
    ```    
5. In identifying the top 5 Barangays with the highest densities per Region, we use the arrange, groupby, and slice 
    ```sh
      #Top 5 per Region
      per_region <- population_3 %>%
                    arrange(desc(density)) %>% 
                    group_by(region) %>%
                    slice(1:5)
      per_region
    ```    
6. We now write the three top 5 tables into a csv file.
    ```sh
      #Writing the 'top_barangay' into a csv format
      write.csv(top_barangay,"top_barangay.csv", row.names = FALSE)
    ```
    ```sh
      #Writing the 'top_per_city' into a csv format
      write.csv(per_city,"top_per_city.csv", row.names = FALSE)
    ```
    ```sh
      #Writing the 'top_per_region' into a csv format
      write.csv(per_region,"top_per_region.csv", row.names = FALSE)
    ```
    
Summary

We are able to identify the top 5 barangays with the highest density overall, per city, and per region by using different functions and libraries in R.